name: sample_navigation_system
description: A Flutter application with GoRouter and Riverpod navigation system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^15.1.3
  flutter_riverpod: ^2.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  go_router_builder: ^3.0.0
  build_runner: ^2.4.0

flutter:
  uses-material-design: true